[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && yarn install --frozen-lockfile && yarn run build:production"

[deploy]
startCommand = "sh railway-start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/api/client"
timeout = 100
interval = 30
